### ISSUE TITLE
"list index out of range" for account/auth arguments

### ISSUE THREAD

**Issue by jonathanwcrane** [Ashex/pokemongo-map-docker#16]
So this is a new one.  I have been running your containers successfully for weeks.  However today when I fired one up, the logs ended with the message:

```
Traceback (most recent call last):
  File "runserver.py", line 22, in <module>
    from pogom.app import Pogom
  File "/app/pogom/app.py", line 17, in <module>
    from .models import Pokemon, Gym, Pokestop, ScannedLocation, MainWorker, WorkerStatus
  File "/app/pogom/models.py", line 22, in <module>
    from .customLog import printPokemon
  File "/app/pogom/customLog.py", line 5, in <module>
    args = get_args()
  File "/app/pogom/utils.py", line 38, in wrapper
    rv = function(*args)
  File "/app/pogom/utils.py", line 263, in get_args
    args.accounts.append({'username': username, 'password': args.password[i], 'auth_service': args.auth_service[i]})
IndexError: list index out of range
```

I suspect that the app is looking for the account info in a different way due to a recent PR merge.  Can you look into this please?

**Comment by jonathanwcrane** [comment]
OK so it still works, I believe the issue is that previously, the default AUTH SERVICE was ptc so you could leave that part of the command line out, which is what I did for brevity.  Now it's looking for it explicitly.
